### ISSUE TITLE
No notifications in the list, sporadic issue

### ISSUE THREAD

**Issue by goodwillcoding** [Selenium-H/Notification-Center#10]
Occasionally (usually after laptop sleep and unlock), the message list will no longer show incoming notification thought a the notification "dot" next to the icon will appear.

My guess some edge case is missing but I since I can not reproduce this reliably it's hard to debug.

Only errors I've seen in the logs are:
```
Apr 18 09:22:27 machine gnome-shell[27680]: st_widget_get_theme_node called on the widget [0x560f75807f80 StIcon] which is not in the stage.
Apr 18 09:22:27 machine gnome-shell[27680]: st_widget_get_theme_node called on the widget [0x560f75807f80 StIcon] which is not in the stage.
Apr 18 09:22:27 machine gnome-shell[27680]: st_widget_get_theme_node called on the widget [0x560f75807f80 StIcon] which is not in the stage.
Apr 18 09:22:27 machine gnome-shell[27680]: st_widget_get_theme_node called on the widget [0x560f75807f80 StIcon] which is not in the stage.
```

Given the log I am playing with, wrapping https://github.com/Selenium-H/Notification-Center/blob/0500568fa8f16292bce946aa58d4de95b71f6612/notification-center%40Selenium-H/extension.js#L165 in try/catch and see if that helps, but I thought I'd report it

**Comment by goodwillcoding** [comment]
My general suspicion is not the theme bit above, but that the messageList will need to be added to the widget based on some specific signal.

**Comment by Selenium-H** [comment]
That might be the case.

The errors in logs are probably due to "dot" indicator being removed ( will update a fix shortly ) from date time Menu.

**Comment by axelitus** [comment]
I have this issue with latest extension installed from the gnome extensions page.

I'm using Ubuntu 19.04 with Arc-Dark theme and my issue is not sporadic. The notifications list is always empty:
![image](https://user-images.githubusercontent.com/732441/57540733-fba4d500-7312-11e9-8820-0ff6d9cad4c7.png)

The notification count works fine, but I haven't seen any notification yet, it just doesn't work for me.

**Comment by Selenium-H** [comment]
@axelitus Are there any errors in log ? Does the issue exist with all other extensions disabled or after shell restart or with default extension preferences ?

**Comment by axelitus** [comment]
@Selenium-H I've disabled all other extensions and compiled ran an npm process that throws a notification but it still does the same in which the notification "exists", but it is not shown. The logs show no error either (2nd screenshot is running the gnome-shell logs):
![image](https://user-images.githubusercontent.com/732441/57625616-d81f9b80-7559-11e9-8c3f-b93a429a8b38.png)
![image](https://user-images.githubusercontent.com/732441/57625648-e79ee480-7559-11e9-80ef-96c5e7ca3724.png)

For the default settings I've only changed the dot for the notification count, have re3verted but still the same result.

**Comment by Selenium-H** [comment]
@axelitus  Thanks for confirming.

**Comment by axelitus** [comment]
@Selenium-H sure thing. If you need anything else just ask because at the moment it is sadly unusable for me :(

**Comment by Selenium-H** [comment]
@axelitus I am trying to replicate the issue. I don't understand what's causing the list to always disappear.

**Comment by axelitus** [comment]
@Selenium-H yeah, it's really odd and I did not find any logs, though I'm no expert when it comes to gnome.

**Comment by Selenium-H** [comment]
Last commit added a workaround to reload message list. Right clicking on panel icon reloads message list and brings back disappeared message list due to suspend.

**Comment by axelitus** [comment]
I have tried the new version (git clone + manually install + disable + enable extension) and I got the same result, the notifications are not shown:

![image](https://user-images.githubusercontent.com/732441/58131048-406a1f00-7be3-11e9-9ca4-636144d2f9bb.png)

I haven't restarted though, I'm not sure if it would help...

**Comment by goodwillcoding** [comment]
@axelitus I really do not think you have the same issue as me, mine happens very specifically after suspend. Maybe it makes sense for you to open a different issue and not confuse the two

**Comment by goodwillcoding** [comment]
@Selenium-H I am going to test the last fix my guess that doing element shuffling for every click might end up with too much overhead. I've been playing with multiple signals but the testing is super slow since it looks like it takes specific timed situations to reproduce.

**Comment by goodwillcoding** [comment]
@Selenium-H so after 2 weeks of testing I can report that the approach for this does work.

**Comment by Selenium-H** [comment]
@axelitus I can't reproduce the issue you are having. Tested it in ubuntu 19.04 , its working fine.

**Comment by thmhoag** [comment]
@axelitus Came across this issue as I was having the exact same problem, although I'm on Ubuntu 18.04.

I ended up completely removing the extension, cleaning the folder out of `.local/share/gnome-shell/extensions`, restarting the shell, and then installing per the instructions in the readme (including restarting the shell again) and my notifications are now working.

Previously I used Firefox to install the extension from the https://extensions.gnome.org/ site, I suspect it didn't install it correctly and somehow corrupted the extensions directory but I'm not certain.

**Comment by axelitus** [comment]
@Selenium-H, sorry for the late response, I've been swamped with work.

@thmhoag I followed your instructions and it worked! Thanks for the tip.
![image](https://user-images.githubusercontent.com/732441/59712332-9de98f80-91d2-11e9-8bf7-2ddeec473923.png)

I had previously used the https://extensions.gnome.org method. This time manually and with the script, everything worked. I don't know if the package published is broken or something, but I did notice some diffs to what I had (I did not erase the old folder for comparison):
![image](https://user-images.githubusercontent.com/732441/59712605-2cf6a780-91d3-11e9-81ac-aa8c12155021.png)

Example of differences:
![image](https://user-images.githubusercontent.com/732441/59712750-70e9ac80-91d3-11e9-8c16-33da4166fda7.png)

@Selenium-H I don't know if you need me to share the differences or with this info, we can close the issue and then check the published version in the extensions site of gnome.

**Comment by Selenium-H** [comment]
@axelitus Thanks for the update. I don't think the package in https://extensions.gnome.org/ is broken since I have installed the extension from there while testing during a few initial times, however I will update it shortly.

**Comment by axelitus** [comment]
@Selenium-H great! Let me know when you do if you need me to test installing through gnome extension's site.

**Comment by axelitus** [comment]
I'm glad to report back that I have reinstalled the extension from https://extensions.gnome.org/ on my lap and it worked perfectly:

![image](https://user-images.githubusercontent.com/732441/59964936-39c61480-94cd-11e9-9c66-350028c2131e.png)

I think some changes you did fixed it for me and it just needed to be updated in the for it to download them.

Thanks for all your hard work, the extension is great!

**Comment by terencode** [comment]
Unfortunately, with the git version re-installed I can still reproduce the issue.

**Comment by Selenium-H** [comment]
With the last commit the extension now automatically detects empty notification list and rebuilds it.

**Comment by Selenium-H** [comment]
The previous commit had an error and has been fixed in this commit.

**Comment by goodwillcoding** [comment]
Sadly Issue is back, trying to figure out the scenario more clearly

**Comment by Selenium-H** [comment]
@goodwillcoding Does the notification center remains empty even while opening it by clicking ( left click ) on  indicator or only when you open it by using keyboard (like opening other menu and moving to it.) ?
Can you please confirm, if you are using this commit https://github.com/Selenium-H/Notification-Center/commit/dc3bfc19ffbef22b689875f5f3d5fb5a0c323781 of extension.js ?

**Comment by goodwillcoding** [comment]
@Selenium-H yes to remain empty on openening..

however I did not have commit dc3bfc1 . I just pulled the changes and will let you know. The problem is sporadic and takes some time to appear (usually post sleep, so it might be a few days)

**Comment by Selenium-H** [comment]
@goodwillcoding Thanks for confirming.
You can check logs for  `Detected missing messages. Rebuilding`   
It is displayed while left clicking the indicator when the extension detects missing messages and rebuilds the notifications list.
The issue might exist on opening it via keyboard to which I will update a fix

**Comment by Selenium-H** [comment]
@goodwillcoding Thanks for confirming. 

With last commit in [Version-17-not-final](https://github.com/Selenium-H/Notification-Center/tree/Version-17-not-final) branch the workaround works while opening the menu everytime.

**Comment by Selenium-H** [comment]
Last commit in [Version-17-not-final](https://github.com/Selenium-H/Notification-Center/tree/Version-17-not-final) fixes this issue. The visibility of sections are set to true everytime the menu is opened .
